=== api-evangelist/amazon-opensearch/json-schema/openapi-update-elasticsearch-domain-config-request-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-opensearch/refs/heads/main/json-schema/openapi-update-elasticsearch-domain-config-request-schema.json",
  "title": "UpdateElasticsearchDomainConfigRequest",
  "description": "Container for the parameters to the <code><a>UpdateElasticsearchDomain</a></code> operation. Specifies the type and number of instances in the domain cluster.",
  "type": "object",
  "properties": {
    "ElasticsearchClusterConfig": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ElasticsearchClusterConfig"
        },
        {
          "description": "The type and number of instances to instantiate for the domain cluster."
        }
      ]
    },
    "EBSOptions": {
      "allOf": [
        {
          "$ref": "#/components/schemas/EBSOptions"
        },
        {
          "description": "Specify the type and size of the EBS volume that you want to use. "
        }
      ]
    },
    "SnapshotOptions": {
      "allOf": [
        {
          "$ref": "#/components/schemas/SnapshotOptions"
        },
        {
          "description": "Option to set the time, in UTC format, for the daily automated snapshot. Default value is <code>0</code> hours. "
        }
      ]
    },
    "VPCOptions": {
      "allOf": [
        {
          "$ref": "#/components/schemas/VPCOptions"
        },
        {
          "description": "Options to specify the subnets and security groups for VPC endpoint. For more information, see <a href=\"http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-vpc.html#es-creating-vpc\" target=\"_blank\">Creating a VPC</a> in <i>VPC Endpoints for Amazon Elasticsearch Service Domains</i>"
        }
      ]
    },
    "CognitoOptions": {
      "allOf": [
        {
          "$ref": "#/components/schemas/CognitoOptions"
        },
        {
          "description": "Options to specify the Cognito user and identity pools for Kibana authentication. For more information, see <a href=\"http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-cognito-auth.html\" target=\"_blank\">Amazon Cognito Authentication for Kibana</a>."
        }
      ]
    },
    "AdvancedOptions": {
      "allOf": [
        {
          "$ref": "#/components/schemas/AdvancedOptions"
        },
        {
          "description": "Modifies the advanced option to allow references to indices in an HTTP request body. Must be <code>false</code> when configuring access to individual sub-resources. By default, the value is <code>true</code>. See <a href=\"http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-createupdatedomains.html#es-createdomain-configure-advanced-options\" target=\"_blank\">Configuration Advanced Options</a> for more information."
        }
      ]
    },
    "AccessPolicies": {
      "allOf": [
        {
          "$ref": "#/components/schemas/PolicyDocument"
        },
        {
          "description": "IAM access policy as a JSON-formatted string."
        }
      ]
    },
    "LogPublishingOptions": {
      "allOf": [
        {
          "$ref": "#/components/schemas/LogPublishingOptions"
        },
        {
          "description": "Map of <code>LogType</code> and <code>LogPublishingOption</code>, each containing options to publish a given type of Elasticsearch log."
        }
      ]
    },
    "DomainEndpointOptions": {
      "allOf": [
        {
          "$ref": "#/components/schemas/DomainEndpointOptions"
        },
        {
          "description": "Options to specify configuration that will be applied to the domain endpoint."
        }
      ]
    },
    "AdvancedSecurityOptions": {
      "allOf": [
        {
          "$ref": "#/components/schemas/AdvancedSecurityOptionsInput"
        },
        {
          "description": "Specifies advanced security options."
        }
      ]
    },
    "NodeToNodeEncryptionOptions": {
      "allOf": [
        {
          "$ref": "#/components/schemas/NodeToNodeEncryptionOptions"
        },
        {
          "description": "Specifies the NodeToNodeEncryptionOptions."
        }
      ]
    },
    "EncryptionAtRestOptions": {
      "allOf": [
        {
          "$ref": "#/components/schemas/EncryptionAtRestOptions"
        },
        {
          "description": "Specifies the Encryption At Rest Options."
        }
      ]
    },
    "AutoTuneOptions": {
      "allOf": [
        {
          "$ref": "#/components/schemas/AutoTuneOptions"
        },
        {
          "description": "Specifies Auto-Tune options."
        }
      ]
    },
    "DryRun": {
      "allOf": [
        {
          "$ref": "#/components/schemas/DryRun"
        },
        {
          "description": " This flag, when set to True, specifies whether the <code>UpdateElasticsearchDomain</code> request should return the results of validation checks without actually applying the change. This flag, when set to True, specifies the deployment mechanism through which the update shall be applied on the domain. This will not actually perform the Update. "
        }
      ]
    }
  }
}

=== api-evangelist/amazon-opensearch/examples/openapi-update-elasticsearch-domain-config-request-example.json
{
  "ElasticsearchClusterConfig": "example-string",
  "EBSOptions": "example-string",
  "SnapshotOptions": "example-string",
  "VPCOptions": "example-string",
  "CognitoOptions": "example-string",
  "AdvancedOptions": "example-string",
  "AccessPolicies": "example-string",
  "LogPublishingOptions": "example-string",
  "DomainEndpointOptions": "example-string",
  "AdvancedSecurityOptions": "example-string",
  "NodeToNodeEncryptionOptions": "example-string",
  "EncryptionAtRestOptions": "example-string",
  "AutoTuneOptions": "example-string",
  "DryRun": "example-string"
}
