=== api-evangelist/amazon-opensearch/json-schema/openapi-package-details-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-opensearch/refs/heads/main/json-schema/openapi-package-details-schema.json",
  "title": "PackageDetails",
  "description": "Basic information about a package.",
  "type": "object",
  "properties": {
    "PackageID": {
      "allOf": [
        {
          "$ref": "#/components/schemas/PackageID"
        },
        {
          "description": "Internal ID of the package."
        }
      ]
    },
    "PackageName": {
      "allOf": [
        {
          "$ref": "#/components/schemas/PackageName"
        },
        {
          "description": "User specified name of the package."
        }
      ]
    },
    "PackageType": {
      "allOf": [
        {
          "$ref": "#/components/schemas/PackageType"
        },
        {
          "description": "Currently supports only TXT-DICTIONARY."
        }
      ]
    },
    "PackageDescription": {
      "allOf": [
        {
          "$ref": "#/components/schemas/PackageDescription"
        },
        {
          "description": "User-specified description of the package."
        }
      ]
    },
    "PackageStatus": {
      "allOf": [
        {
          "$ref": "#/components/schemas/PackageStatus"
        },
        {
          "description": "Current state of the package. Values are COPYING/COPY_FAILED/AVAILABLE/DELETING/DELETE_FAILED"
        }
      ]
    },
    "CreatedAt": {
      "allOf": [
        {
          "$ref": "#/components/schemas/CreatedAt"
        },
        {
          "description": "Timestamp which tells creation date of the package."
        }
      ]
    },
    "LastUpdatedAt": {
      "$ref": "#/components/schemas/LastUpdated"
    },
    "AvailablePackageVersion": {
      "$ref": "#/components/schemas/PackageVersion"
    },
    "ErrorDetails": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ErrorDetails"
        },
        {
          "description": "Additional information if the package is in an error state. Null otherwise."
        }
      ]
    }
  }
}

=== api-evangelist/amazon-opensearch/examples/openapi-package-details-example.json
{
  "PackageID": "resource-abc123",
  "PackageName": "my-resource",
  "PackageType": "standard",
  "PackageDescription": "example-string",
  "PackageStatus": "active",
  "CreatedAt": "example-string",
  "LastUpdatedAt": "example-ref",
  "AvailablePackageVersion": "example-ref",
  "ErrorDetails": "example-string"
}
